language: node_js
node_js:
  - 7.8.0
sudo: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email:
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  - npm install -g codecov
  - npm install coveralls
script:
  - npm run cover
after_script:
  - codecov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run docs
after_success:
  - git add README.md
  - git config --global user.name travis
  - git config --global user.email travis
  - git commit -m "docs(README): sync"
  - git remote add origin https://arlac77:${GH_TOKEN}@github.com/arlac77/named-conf.git
  - git push origin
  - npm run semantic-release
